//
// This file was generated by the JavaTM Architecture for fiXML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.15 at 12:39:42 PM WAT 
//


package com.fiMock.fiXMLResponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for executeFinacleScript_CustomData complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="executeFinacleScript_CustomData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="signId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SuccessOrFailure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mainHol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prevHol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LienB2kId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType ( XmlAccessType.FIELD )
@XmlType ( name = "executeFinacleScript_CustomData", propOrder = {
	  "signId" ,
	  "mainHol" ,
	  "prevHol" ,
	  "lienB2KId",
	  "solId",
	  "crncyCode",
	  "acctName",
	  "freezeCode",
	  "AcctBal",
	  "schmType",
	  "schmCode",
	  "schmCodeDesc",
	  "acctOfficerCode",
	  "acctOfficerCodeDesc",
	  "acctBrokerCode",
	  "brokerCodeDesc",
	  "acctStatus",
	  "acctSMSStatus",
	  "acctEmailStatus",
	  "successOrFailure"
} )
public class ExecuteFinacleScriptCustomData {
	
	@XmlElement ( required = true )
	protected String signId;
	@XmlElement ( name = "SuccessOrFailure", required = true )
	protected String successOrFailure;
	@XmlElement ( required = true )
	protected String mainHol;
	@XmlElement ( required = true )
	protected String prevHol;
	@XmlElement ( name = "LienB2kId", required = true )
	protected String lienB2KId;
	@XmlElement ( name = "AcctBal", required = true )
	protected String AcctBal;
	@XmlElement ( name = "acctName", required = true )
	protected String acctName;
	@XmlElement ( name = "solId", required = true )
	protected String solId;
	@XmlElement ( name = "crncyCode", required = true )
	protected String crncyCode;
	@XmlElement ( name = "freezeCode", required = true )
	protected String freezeCode;
	@XmlElement ( name = "schmType", required = true )
	protected String schmType;
	@XmlElement ( name = "schmCode", required = true )
	protected String schmCode;
	@XmlElement ( name = "schmCodeDesc", required = true )
	protected String schmCodeDesc;
	@XmlElement ( name = "acctOfficerCode", required = true )
	protected String acctOfficerCode;
	@XmlElement ( name = "acctOfficerCodeDesc", required = true )
	protected String acctOfficerCodeDesc;
	@XmlElement ( name = "acctBrokerCode", required = true )
	protected String acctBrokerCode;
	@XmlElement ( name = "brokerCodeDesc", required = true )
	protected String brokerCodeDesc;
	@XmlElement ( name = "acctStatus", required = true )
	protected String acctStatus;
	@XmlElement ( name = "acctSMSStatus", required = true )
	protected String acctSMSStatus;
	@XmlElement ( name = "acctEmailStatus", required = true )
	protected String acctEmailStatus;
	
	
	/**
	 * Gets the value of the signId property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getSignId () {
		return signId;
	}
	
	/**
	 * Sets the value of the signId property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setSignId ( String value ) {
		this.signId = value;
	}
	
	/**
	 * Gets the value of the successOrFailure property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getSuccessOrFailure () {
		return successOrFailure;
	}
	
	/**
	 * Sets the value of the successOrFailure property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setSuccessOrFailure ( String value ) {
		this.successOrFailure = value;
	}
	
	/**
	 * Gets the value of the mainHol property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getMainHol () {
		return mainHol;
	}
	
	/**
	 * Sets the value of the mainHol property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setMainHol ( String value ) {
		this.mainHol = value;
	}
	
	/**
	 * Gets the value of the prevHol property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getPrevHol () {
		return prevHol;
	}
	
	/**
	 * Sets the value of the prevHol property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setPrevHol ( String value ) {
		this.prevHol = value;
	}
	
	/**
	 * Gets the value of the lienB2KId property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getLienB2KId () {
		return lienB2KId;
	}
	
	/**
	 * Sets the value of the lienB2KId property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setLienB2KId ( String value ) {
		this.lienB2KId = value;
	}
	
	/**
	 * Gets the value of the AcctBal property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getAcctBal () {
		return AcctBal;
	}
	
	/**
	 * Sets the value of the AcctBal property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setAcctBal ( String value ) {
		this.AcctBal = value;
	}
	
	/**
	 * Gets the value of the acctName property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getAcctName () {
		return acctName;
	}
	
	/**
	 * Sets the value of the acctName property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setAcctName ( String value ) {
		this.acctName = value;
	}
	
	public String getSolId () {
		return solId;
	}
	
	public void setSolId ( String solId ) {
		this.solId = solId;
	}
	
	public String getCrncyCode () {
		return crncyCode;
	}
	
	public void setCrncyCode ( String crncyCode ) {
		this.crncyCode = crncyCode;
	}
	
	public String getFreezeCode () {
		return freezeCode;
	}
	
	public void setFreezeCode ( String freezeCode ) {
		this.freezeCode = freezeCode;
	}
	
	public String getSchmType () {
		return schmType;
	}
	
	public void setSchmType ( String schmType ) {
		this.schmType = schmType;
	}
	
	public String getSchmCode () {
		return schmCode;
	}
	
	public void setSchmCode ( String schmCode ) {
		this.schmCode = schmCode;
	}
	
	public String getAcctOfficerCode () {
		return acctOfficerCode;
	}
	
	public void setAcctOfficerCode ( String acctOfficerCode ) {
		this.acctOfficerCode = acctOfficerCode;
	}
	
	public String getAcctOfficerCodeDesc () {
		return acctOfficerCodeDesc;
	}
	
	public void setAcctOfficerCodeDesc ( String acctOfficerCodeDesc ) {
		this.acctOfficerCodeDesc = acctOfficerCodeDesc;
	}
	
	public String getAcctBrokerCode () {
		return acctBrokerCode;
	}
	
	public void setAcctBrokerCode ( String acctBrokerCode ) {
		this.acctBrokerCode = acctBrokerCode;
	}
	
	public String getBrokerCodeDesc () {
		return brokerCodeDesc;
	}
	
	public void setBrokerCodeDesc ( String brokerCodeDesc ) {
		this.brokerCodeDesc = brokerCodeDesc;
	}
	
	public String getAcctStatus () {
		return acctStatus;
	}
	
	public void setAcctStatus ( String acctStatus ) {
		this.acctStatus = acctStatus;
	}
	
	public String getAcctSMSStatus () {
		return acctSMSStatus;
	}
	
	public void setAcctSMSStatus ( String acctSMSStatus ) {
		this.acctSMSStatus = acctSMSStatus;
	}
	
	public String getAcctEmailStatus () {
		return acctEmailStatus;
	}
	
	public void setAcctEmailStatus ( String acctEmailStatus ) {
		this.acctEmailStatus = acctEmailStatus;
	}
	
	public String getSchmCodeDesc () {
		return schmCodeDesc;
	}
	
	public void setSchmCodeDesc ( String schmCodeDesc ) {
		this.schmCodeDesc = schmCodeDesc;
	}
	
	@Override
	public String toString () {
		return "\n<signId>" + signId + "</signId>\n" +
			  "<SuccessOrFailure>" + successOrFailure + "</SuccessOrFailure>\n" +
			  "<mainHol>" + mainHol + "</mainHol>\n" +
			  "<prevHol>" + prevHol + "</prevHol>\n"  +
			  "<LienB2kId>" + lienB2KId + "</LienB2kId>\n" +
			  "<AcctBal>" + AcctBal + "</AcctBal>\n" +
			  "<acctName>" + acctName + "</acctName>\n" +
			  "<solId>" + solId + "</solId>\n" +
			  "<crncyCode>" + crncyCode + "</crncyCode>\n" +
			  "<freezeCode>" + freezeCode + "</freezeCode>\n" +
			  "<schmType>" + schmType + "</schmType>\n" +
			  "<schmCode>" + schmCode + "</schmCode>\n" +
			  "<schmCodeDesc>" + schmCodeDesc + "</schmCodeDesc>\n" +
			  "<acctOfficerCode>" + acctOfficerCode + "</acctOfficerCode>\n" +
			  "<acctOfficerCodeDesc>" + acctOfficerCodeDesc + "</acctOfficerCodeDesc>\n" +
			  "<acctBrokerCode>" + acctBrokerCode + "</acctBrokerCode>\n" +
			  "<brokerCodeDesc>" + brokerCodeDesc + "</brokerCodeDesc>\n" +
			  "<acctStatus>" + acctStatus + "</acctStatus>\n" +
			  "<acctSMSStatus>" + acctSMSStatus + "</acctSMSStatus>\n" +
			  "<acctEmailStatus>" + acctEmailStatus + "</acctEmailStatus>\n";
	}
}
