//
// This file was generated by the JavaTM Architecture for fiXML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.15 at 12:39:42 PM WAT 
//


package com.fiMock.fiXMLResponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for updateCorpCustomerResponse complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="updateCorpCustomerResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CustomerModOutputStruct" type="{http://webservice.fiusb.ci.infosys.com}CustomerModOutputStruct"/>
 *         &lt;element name="updateCorpCustomer_CustomData" type="{http://www.w3.org/2001/XMLSchema}updateCorpCustomer_CustomData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType ( XmlAccessType.FIELD )
@XmlType ( name = "updateCorpCustomerResponse", propOrder = {
	  "CustomerModOutputStruct" ,
	  "updateCorpCustomer_CustomData"
} )
public class updateCorpCustomerResponse {
	
	@XmlElement ( name = "CustomerModOutputStruct", required = true )
	protected CustomerModOutputStruct CustomerModOutputStruct;
	@XmlElement ( name = "updateCorpCustomer_CustomData", required = true )
	protected updateCorpCustomer_CustomData updateCorpCustomer_CustomData;
	
	/**
	 * Gets the value of the CustomerModOutputStruct property.
	 *
	 * @return possible object is
	 * {@link CustomerModOutputStruct }
	 */
	public CustomerModOutputStruct getCustomerModOutputStruct () {
		return CustomerModOutputStruct;
	}
	
	/**
	 * Sets the value of the CustomerModOutputStruct property.
	 *
	 * @param value allowed object is
	 *              {@link CustomerModOutputStruct }
	 */
	public void setCustomerModOutputStruct ( CustomerModOutputStruct value ) {
		this.CustomerModOutputStruct = value;
	}
	
	/**
	 * Gets the value of the updateCorpCustomer_CustomData property.
	 *
	 * @return possible object is
	 * {@link updateCorpCustomer_CustomData }
	 */
	public updateCorpCustomer_CustomData getupdateCorpCustomer_CustomData () {
		return updateCorpCustomer_CustomData;
	}
	
	/**
	 * Sets the value of the updateCorpCustomer_CustomData property.
	 *
	 * @param value allowed object is
	 *              {@link updateCorpCustomer_CustomData }
	 */
	public void setupdateCorpCustomer_CustomData ( updateCorpCustomer_CustomData value ) {
		this.updateCorpCustomer_CustomData = value;
	}
	
	@Override
	public String toString () {
		return "\n<CustomerModOutputStruct>" + CustomerModOutputStruct + "</CustomerModOutputStruct>\n" +
			  "<updateCorpCustomer_CustomData/>\n";
	}
}
