//
// This file was generated by the JavaTM Architecture for fiXML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.15 at 12:39:42 PM WAT 
//


package com.fiMock.fiXMLResponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for verifyCustomerDetailsResponse complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="verifyCustomerDetailsResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CustomerVerifyRs" type="{http://webservice.fiusb.ci.infosys.com}CustomerVerifyRs"/>
 *         &lt;element name="verifyCustomerDetails_CustomData" type="{http://www.w3.org/2001/XMLSchema}verifyCustomerDetails_CustomData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType ( XmlAccessType.FIELD )
@XmlType ( name = "verifyCustomerDetailsResponse", propOrder = {
	  "CustomerVerifyRs" ,
	  "verifyCustomerDetails_CustomData"
} )
public class verifyCustomerDetailsResponse {
	
	@XmlElement ( name = "CustomerVerifyRs", required = true )
	protected CustomerVerifyRs CustomerVerifyRs;
	@XmlElement ( name = "verifyCustomerDetails_CustomData", required = true )
	protected verifyCustomerDetails_CustomData verifyCustomerDetails_CustomData;
	
	/**
	 * Gets the value of the CustomerVerifyRs property.
	 *
	 * @return possible object is
	 * {@link CustomerVerifyRs }
	 */
	public CustomerVerifyRs getCustomerModOutputStrucCustomerVerifyRst () {
		return CustomerVerifyRs;
	}
	
	/**
	 * Sets the value of the CustomerVerifyRs property.
	 *
	 * @param value allowed object is
	 *              {@link CustomerVerifyRs }
	 */
	public void setCustomerVerifyRs ( CustomerVerifyRs value ) {
		this.CustomerVerifyRs = value;
	}
	
	/**
	 * Gets the value of the verifyCustomerDetails_CustomData property.
	 *
	 * @return possible object is
	 * {@link verifyCustomerDetails_CustomData }
	 */
	public verifyCustomerDetails_CustomData getverifyCustomerDetails_CustomData () {
		return verifyCustomerDetails_CustomData;
	}
	
	/**
	 * Sets the value of the verifyCustomerDetails_CustomData property.
	 *
	 * @param value allowed object is
	 *              {@link verifyCustomerDetails_CustomData }
	 */
	public void setverifyCustomerDetails_CustomData ( verifyCustomerDetails_CustomData value ) {
		this.verifyCustomerDetails_CustomData = value;
	}
	
	@Override
	public String toString () {
		return "\n<CustomerVerifyRs>" + CustomerVerifyRs + "</CustomerVerifyRs>\n" +
			  "<verifyCustomerDetails_CustomData/>\n";
	}
}
